version: '3.8'

services:
  # Frontend web service
  frontend-web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.web
    ports:
      - "4080:80"
    restart: always
    depends_on:
      - backend

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4081:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://nutrition_user:jK8p$2xL9#Qr7ZvT5yE3bN6*mW4dF@db:5432/nutrition_tracker
      - JWT_SECRET=eT7pM3kR8sL2gF9dH5jN6bV1cX4zQ0yU
      - PORT=3000
    depends_on:
      - db

  # Database service
  db:
    image: postgres:13-alpine
    ports:
      - "4082:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=nutrition_user
      - POSTGRES_PASSWORD=jK8p$2xL9#Qr7ZvT5yE3bN6*mW4dF
      - POSTGRES_DB=nutrition_tracker
    restart: always

volumes:
  postgres_data: